### ISSUE TITLE
Getting Errors

### ISSUE THREAD

**Issue by sils** [coala-analyzer/coala-gedit#16]
CC @AbdealiJK 

```
(gedit:21114): libpeas-WARNING **: Error initializing Python Plugin Loader: PyGObject initialization failed
ImportError: could not import gobject (error was: ImportError("No module named 'gi'",))

(gedit:21114): libpeas-WARNING **: Please check the installation of all the Python related packages required by libpeas and try again

(gedit:21114): libpeas-WARNING **: Loader 'python3' is not a valid PeasPluginLoader instance
```

@sims1253 can you reproduce?

**Comment by AbdealiLoKo** [comment]
What's your OS and system info ?

It says "ImportError("No module named 'gi'",))" ... so have you installed
it ?

Also, It looks like your gedit does not support python3 plugins and only
supports python plugins

**Comment by sils** [comment]
But didn't this plugin work before? :/

**Comment by sils** [comment]
I'm on ArchLinux with GNOME 3.20.1

**Comment by AbdealiLoKo** [comment]
It did work before (You showed it in FOSSASIA). Hence I think it is a
system specific problem.

**Most probable cause**: python3-gi not installed

This can be tested with:

python3 -c "import gi"

**Comment by sils** [comment]
oh is there a pip package for python-gi? I tried looking into system packages but everything related was there and there's no requirements.txt

**Comment by AbdealiLoKo** [comment]
There is no pip package for python-gi
It uses autoconf, not setuptools/distutils

You either compile by source or use the distro's package manager

**Comment by sils** [comment]
FWIW it works for @sims1253 with the same system... maybe I did something wrong with the venv...

**Comment by AbdealiLoKo** [comment]
Cool, can we close this then /

**Comment by sils** [comment]
no, still doesn't work for me and if we ever find a solution we should add some documentation for this. It's not our fault but some docs are in order.

**Comment by SanketDG** [comment]
@sils Did you have time to look into this, and possibly have found a solution?

**Comment by sils** [comment]
not so far, if noone can reproduce this we should close it

**Comment by SanketDG** [comment]
Closing this then.

Edit: A quick google search says to install `python-gobject`/`python2-gobject` on Arch.
